// Writes ipad.html and play.html from index.html: the same composition, its root sized to that store's video frame
// and window.FMT set before the script (fit.js has the formats). Run after every edit to index.html:
//   node make-formats.mjs
import fs from 'fs';
const src = fs.readFileSync(new URL('./index.html', import.meta.url), 'utf8');
for (const [fmt, w, h] of [['ipad', 1200, 1600], ['play', 1080, 1920]]) {
  let s = src;
  const sub = (a, b) => { if (!s.includes(a)) throw new Error(fmt + ': missing ' + a); s = s.split(a).join(b); };
  sub('content="width=886, height=1920"', `content="width=${w}, height=${h}"`);
  sub('html,body{width:886px;height:1920px;', `html,body{width:${w}px;height:${h}px;`);
  sub('#root{position:relative;width:886px;height:1920px;', `#root{position:relative;width:${w}px;height:${h}px;`);
  sub('data-width="886" data-height="1920"', `data-width="${w}" data-height="${h}"`);
  sub('<script src="fit.js"></script>', `<script src="fit.js"></script>\n<script>window.FMT = '${fmt}';</script>`);
  s = s.replace('<!doctype html>', '<!doctype html>\n<!-- generated by make-formats.mjs from index.html; edit index.html, not this file -->');
  fs.writeFileSync(new URL(`./${fmt}.html`, import.meta.url), s);
}
console.log('wrote ipad.html, play.html');
