/* NeroGym feasibility brief — the one place figures live.
   GBP, ex VAT (a VAT-registered operator recovers it). "est." marks a figure nobody publishes,
   derived from the sources cited beside it. Dated 16 September 2026. Every web figure was read
   from a search-result snippet on that date because direct page fetches were blocked in the
   session; re-quote from the live page before anything goes in front of a lender.
   Structure: phases → capex rows (one-off, chronological) · opex rows (monthly, ex rent) ·
   ancillary (monthly income) · assumptions · pricing · competitors. */
window.NG = {
  meta: { date: '16 September 2026', sqft: 5000, sqm: 465, capMembers: 500, sqftPerMember: 10 },

  /* X. The premises rent is the figure the whole brief hangs off. Default is the one in-band
     Stockport unit with a published rent (Balmoral Trading Estate, Bredbury, 5,824 sq ft, £3,750 pcm). */
  lease: { default: 3750, min: 2500, max: 9000, step: 250 },

  phases: [
    { id:'0', when:'Month 0', name:'Decide and set up', why:'Nothing below is worth paying for until Eray has answered the three questions on the overview page. The only money here is the paperwork that has to exist whichever way the decision goes.' },
    { id:'1', when:'Months 0–3', name:'Find and secure the premises', why:'The gate. A unit in Class E with clear height, parking, power and drainage, at the seam of an employment cluster and housing. Rent itself is X and is excluded; the deposit and rent-free period are noted, not totalled.' },
    { id:'2', when:'Months 2–5', name:'Design and permissions', why:'Layout, M&E and lighting design, building control, and planning only if the unit is not already in Class E. Equipment with a twelve-week lead time is ordered at the end of this phase.' },
    { id:'3', when:'Months 5–9', name:'Build', why:'Strip out to fit-out: changing block, ventilation and heating, three-phase distribution, the lighting scheme, flooring, mirrors, decoration, joinery, signage. The largest and most variable block.' },
    { id:'4', when:'Months 8–10', name:'Fit and equip', why:'Equipment lands and is installed, then everything that sits on top of the building: access control, CCTV, network, screens, furniture, creator zones, recovery kit, the machine tags.' },
    { id:'5', when:'Months 8–10', name:'Comply, insure, staff', why:'The certificates, licences, policies and people that have to exist before the first member walks in. Several are legal requirements with unlimited fines attached.' },
    { id:'6', when:'Months 7–10', name:'Software and pre-sale', why:'Phase 1 of the Nero app on the door six weeks before opening, and a founder pre-sale that fills a third of the room before the rent starts.' },
    { id:'7', when:'Held back', name:'Contingency and cash reserve', why:'Ten percent on the build for what the survey did not find, and six months of running costs so the ramp does not end the business in month four.' }
  ],

  capex: [
    /* ---- 0 · Decide ---- */
    { id:'inc', ph:'0', item:'Company formation and first filings', note:'Subsidiary of Nero Panda Ltd or a division inside it — see the diligence flag. Companies House fee £100 from 1 Feb 2026; confirmation statement £50.', who:'Companies House direct; accountant to advise on entity', low:100, mid:150, high:600, src:[{t:'yourcompanyformations.co.uk',u:'https://www.yourcompanyformations.co.uk/'}] },
    { id:'tm', ph:'0', item:'Trade mark "NeroGym", classes 41, 9, 44', note:'UK IPO standard fee £205 first class + £60 each further class from 1 Apr 2026. The NEROGYM / NERO register search has not been run; "Nero" is crowded (Caffè Nero holds class 41 marks) so budget for an attorney review.', who:'UK IPO direct (low) · trade mark attorney (mid/high)', low:325, mid:900, high:1500, src:[{t:'UK IPO fees via fosters-solicitors.co.uk',u:'https://www.fosters-solicitors.co.uk/'}], tag:'unverified', tagc:'yl' },
    { id:'acct', ph:'0', item:'Accountant set-up, VAT registration, payroll scheme', note:'One-off onboarding; the monthly fee is on the running-costs page.', who:'Existing NeroPay accountant', low:300, mid:500, high:900, src:[{t:'digiaccounting.co.uk',u:'https://digiaccounting.co.uk/'}], tag:'est.' },

    /* ---- 1 · Premises ---- */
    { id:'clopud', ph:'1', item:'Certificate of Lawfulness (CLOPUD) — confirm the unit is Class E', note:'The cheap way to be certain a gym is lawful without planning. Fee is £274 for a householder-type LDC; a change-of-use CLOPUD is charged at the full-application rate, £610 from 1 Apr 2026. Confirm with Stockport MBC before filing.', who:'Stockport MBC via the Planning Portal', low:274, mid:610, high:680, src:[{t:'Planning Portal fee schedule (Apr 2026 uplift)',u:'https://blog.planningportal.co.uk/'}] },
    { id:'plancons', ph:'1', item:'Planning consultant', note:'Only if the unit is B2/B8 and needs a change of use to E(d). Application fee £610 plus a statement and a parking/transport note. Gyms are refused on parking and highways, so this is not optional if it applies.', who:'Local Greater Manchester planning consultancy', low:0, mid:2500, high:8000, src:[{t:'housey.co.uk commercial change-of-use guide',u:'https://housey.co.uk/'}], tag:'if B2/B8', tagc:'stop' },
    { id:'agent', ph:'1', item:'Search costs, travel, agents', note:'Agents are paid by the landlord. This covers the six site visits and the surveys that do not proceed.', who:'—', low:200, mid:400, high:800, tag:'est.' },
    { id:'sol', ph:'1', item:"Tenant's solicitor — lease, heads of terms, SDLT return, registration", note:'Fixed fees from £1,000 + VAT; £1,500–£2,000 typical; often plus a contribution to the landlord\'s costs. Get a break clause at year 5 and a rent-free period of 3–6 months for the fit-out.', who:'Commercial property solicitor (Wembley Solicitors and Law Superstore publish fixed fees; a Manchester firm will match)', low:1000, mid:1750, high:3000, src:[{t:'wembleysolicitors.com',u:'https://wembleysolicitors.com/'},{t:'thelawsuperstore.co.uk',u:'https://www.thelawsuperstore.co.uk/'}] },
    { id:'struct', ph:'1', item:'Structural engineer — floor loading check', note:'Gym live load 3–5 kN/m² against 2.5 kN/m² for an office. A ground-floor industrial slab usually passes; a mezzanine or first floor usually does not.', who:'Local chartered structural engineer', low:300, mid:600, high:1500, src:[{t:'tvs-gymflooring.com',u:'https://www.tvs-gymflooring.com/'},{t:'myjobquote.co.uk',u:'https://www.myjobquote.co.uk/'}] },
    { id:'asb', ph:'1', item:'Asbestos refurbishment survey (R&D)', note:'Any unit built before 2000. £800–£1,500 for 200–1,000 m² plus about £45 per lab sample.', who:'UKAS-accredited surveyor (Franks Portlock and others)', low:800, mid:1200, high:2000, src:[{t:'franksportlock.co.uk',u:'https://www.franksportlock.co.uk/'}] },
    { id:'epc', ph:'1', item:'Non-domestic EPC', note:'Landlord\'s duty for letting, but budget it in case the unit is being let on an expired certificate.', who:'Level 3/4 non-domestic energy assessor', low:250, mid:400, high:600, src:[{t:'fast-epc.co.uk',u:'https://www.fast-epc.co.uk/'}] },
    { id:'deposit', ph:'1', item:'Rent deposit and first quarter — excluded from the total', note:'Typically 3–6 months\' rent held as deposit on a secondary industrial unit, plus a quarter in advance. At X = £3,750 that is £11,250–£22,500 deposit and £11,250 rent. Shown here so nobody forgets it; not summed because X is not fixed.', who:'Landlord', low:0, mid:0, high:0, tag:'= 3–6 × X', tagc:'yl' },

    /* ---- 2 · Design and permissions ---- */
    { id:'design', ph:'2', item:'Architect / interior designer — layout, finishes, tender drawings', note:'Interior design 6–20% of spend, architect plus CDM 8–12% of build. Priced here as a fixed fee for a 465 m² fit-out with an exposed-services look.', who:'Design Business Interiors (Wigan, 150+ gym projects) · motive8 (Manchester) · Hebs Group (Liverpool) · Blok Projects · a small Manchester architecture practice for a lighter touch', low:6000, mid:14000, high:28000, src:[{t:'toneinteriors.co.uk',u:'https://toneinteriors.co.uk/'},{t:'bhumicalculator.com fit-out costs',u:'https://bhumicalculator.com/countries/united-kingdom/fit-out-costs-per-square-metre'}], tag:'est.' },
    { id:'me', ph:'2', item:'M&E design (ventilation, heating, electrical loads, hot water)', note:'Needed so the HVAC and electrical tenders are like-for-like. Usually inside the designer\'s fee at the high end.', who:'M&E consultant or design-and-build contractor', low:1500, mid:3500, high:6000, tag:'est.' },
    { id:'lightdes', ph:'2', item:'Lighting designer', note:'The scheme is a selling point, so it gets a designer: zones at 3000–4000K, indirect linear, DALI scenes. Fixed fee or 5–8% of lighting spend.', who:'Independent lighting designer; or the LED manufacturer\'s design service (free with supply, less independent)', low:0, mid:2500, high:6000, tag:'est.' },
    { id:'bc', ph:'2', item:'Building Regulations — full plans and inspections', note:'Stockport charges are "individually determined". Registered Building Control Approvers quote 1–1.5% of works value.', who:'Stockport Building Control · Assent · Stroma · Approved Design', low:1800, mid:3000, high:5000, src:[{t:'stockport.gov.uk building control fees',u:'https://www.stockport.gov.uk/'}], tag:'est.' },
    { id:'fs', ph:'2', item:'Fire strategy and means-of-escape check against the access control', note:'Every final exit must open from the inside by one action with no key, code, card or app (BS EN 1125 / EN 179). Maglocks fail-safe on alarm and on power loss. Checked on paper here, installed in the build.', who:'Fire engineer or the fire-risk assessor, engaged early', low:400, mid:800, high:1500, tag:'est.' },
    { id:'advcons', ph:'2', item:'Advertisement consent for the illuminated fascia', note:'May be needed for an illuminated sign; Stockport MBC fee band.', who:'Stockport MBC', low:0, mid:250, high:500, tag:'est.' },

    /* ---- 3 · Build ---- */
    { id:'strip', ph:'3', item:'Strip-out, making good, decoration', note:'Existing partitions out, slab repairs, walls charcoal where kit stands and off-white elsewhere, ceiling and services painted dark.', who:'Main contractor (any of the fit-out firms above, or a good local builder under the designer)', low:8000, mid:12000, high:20000, tag:'est.' },
    { id:'part', ph:'3', item:'Partitions and joinery — reception, lounge, office/store, plant, two creator-zone slat screens', note:'Includes the oak slat feature walls and the acoustic separation of the lounge.', who:'Main contractor; joinery by a local shopfitter', low:10000, mid:18000, high:30000, tag:'est.' },
    { id:'chg', ph:'3', item:'Changing block — 4 showers, 4 WCs in two single-sex ranges, accessible WC, drainage, hot water, tiling, cubicles', note:'Approved Document T (1 Oct 2024) applies on change of use: single-sex toilets with single-sex handwashing, or fully enclosed universal cubicles. Two ranges add roughly £8–15k over one neutral block. Showers £1,500–£4,000 each all-in; cubicles £600–£1,200 supplied.', who:'Main contractor · cubicles: Cubicle Centre, Amwell, Venesta, Cubicle Systems · hot water: commercial unvented bank or heat-pump cylinder', low:45000, mid:60000, high:80000, src:[{t:'RICS on Approved Document T',u:'https://ww3.rics.org/uk/en/journals/built-environment-journal/approved-document-t-non-residential-buildings.html'},{t:'commercialwashroomsltd.co.uk',u:'https://www.commercialwashroomsltd.co.uk/'}] },
    { id:'lock', ph:'3', item:'Lockers — 80 doors, digital lock', note:'Probe 25-door digital bank about £2,500 (£100/door); Link and Helmsman similar; RFID/digital £200–£350 per door at the top.', who:'Probe · Link Lockers · Helmsman · via CS Storage / eSafes', low:8000, mid:12000, high:20000, src:[{t:'csstorage.co.uk gym lockers',u:'https://www.csstorage.co.uk/lockers/lockers-by-function/gym-lockers.html'}] },
    { id:'hvac', ph:'3', item:'Ventilation, cooling and heating', note:'Value: wall splits, mechanical extract to the changing block, four destratification fans, existing gas heater. Mid: multi-zone VRF heat/cool with ducted cassettes (£30–75k), heat-recovery ventilation for changing rooms, destrat fans (£2.8–3.5k each). Premium: full gym-grade air handling at £220–£360/m². This is the line that most often sinks an industrial conversion; get three quotes.', who:'JP Air Conditioning · Inergy · ICE Ltd · a Daikin/Mitsubishi D1 partner in Greater Manchester · Airius for destrat fans', low:30000, mid:60000, high:150000, src:[{t:'accutemp.co.uk commercial AC cost guide',u:'https://accutemp.co.uk/commercial-air-conditioning-cost-guide'},{t:'firstinservice.co.uk',u:'https://firstinservice.co.uk/'},{t:'airius.co.uk',u:'https://www.airius.co.uk/'}] },
    { id:'supply', ph:'3', item:'Electricity supply upgrade to three-phase / higher kVA', note:'Average three-phase upgrade £5,370; £3–8k if the LV main is adjacent, £15–40k if a new feed is needed. Electricity North West quotes within 5 working days. Ask the landlord what the unit already has before viewing twice.', who:'Electricity North West (connections)', low:3000, mid:6000, high:25000, src:[{t:'enwl.co.uk three-phase connection',u:'https://www.enwl.co.uk/get-connected/changing-your-supply/three-phase-power-connection/'},{t:'greensquirrelenergy.co.uk',u:'https://greensquirrelenergy.co.uk/'}] },
    { id:'elec', ph:'3', item:'Electrical installation — distribution boards, sub-mains, small power, fire alarm, emergency lighting, EICR on completion', note:'£45–£60/m² for a mid-spec commercial install with fire alarm and emergency lighting; £60–£80 high spec.', who:'NICEIC contractor under the main contractor', low:21000, mid:26000, high:37000, src:[{t:'elec-mate.com commercial rewire guide',u:'https://www.elec-mate.com/guides/commercial-rewire-cost'}] },
    { id:'light', ph:'3', item:'Lighting scheme — indirect linear, warm zones, DALI dimming, CRI 90+', note:'Standard high-bay LED is £4–8k and looks like a warehouse. The scheme the concept needs is £80–£300 per fitting installed across 120–160 fittings.', who:'LED supply: Tamlite, Thorlux, Whitecroft, Ansell (UK) · install by the electrical contractor', low:12000, mid:30000, high:50000, src:[{t:'calderelectricalservices.co.uk',u:'https://calderelectricalservices.co.uk/'}], tag:'est.' },
    { id:'data', ph:'3', item:'Structured cabling — ~40 Cat6 points for cameras, readers, screens, access points', note:'£60–£200 per point installed.', who:'Network cabling contractor', low:2800, mid:4400, high:7000, src:[{t:'network-data-cabling.co.uk',u:'https://network-data-cabling.co.uk/'}] },
    { id:'floor', ph:'3', item:'Flooring — 140 m² at 40–50 mm under racks and platforms, 230 m² at 20–30 mm, 95 m² cardio, 30 m² turf strip, supplied and fitted', note:'20 mm tile £28–35/m², 30 mm commercial £28–45/m², 43 mm anti-shock ~£73/m², fitting £20–40/m². Trade pricing over 50 m².', who:'Sprung Gym Flooring · Rubber Flooring UK / Rubberco · Gymflooring.co.uk · Pavigym and Ecore via gymequipment.co.uk (premium) · BLK BOX · turf: Wolverson, Heroturfs', low:31000, mid:40000, high:55000, src:[{t:'rubberco.co.uk 2026 price guide',u:'https://rubberco.co.uk/blogs/news/gym-flooring-cost-uk-2026-complete-price-guide-with-cost-calculator'},{t:'gym-flooring.com (Sprung)',u:'https://www.gym-flooring.com/'}] },
    { id:'mirror', ph:'3', item:'Safety-backed mirrors — about 40 m² of wall', note:'Made-to-measure panels from £355; roughly £130–£190/m² fitted.', who:'Gym & Dance Mirrors Direct · commercialmirrors.co.uk · a local glazier', low:5000, mid:6500, high:8000, src:[{t:'commercialmirrors.co.uk',u:'https://commercialmirrors.co.uk/gym-mirrors'}] },
    { id:'acou', ph:'3', item:'Acoustic baffles over the free-weight zone, platform underlay', note:'Industrial units echo. Not optional if the lounge is meant to be quiet.', who:'Acoustic supplier (Soundsorba, Acoustic GRG) via the main contractor', low:2000, mid:6000, high:10000, tag:'est.' },
    { id:'sign', ph:'3', item:'External signage — illuminated built-up N and lockup on the fascia', note:'Built-up aluminium letters £1,980–£2,850 + VAT, halo/face-lit individual letters from £650 each; £4–9k for a 6–8 m gym fascia. Running cost £50–100 a year.', who:'Signs Express Stockport · The Sign Bridge · Universal Signage (Stockport) · Signbox and Applelec (trade, national)', low:4000, mid:6500, high:9000, src:[{t:'completesigns.co.uk shop sign costs',u:'https://completesigns.co.uk/blog/how-much-does-a-shop-sign-cost'},{t:'signsexpress.co.uk/stockport',u:'https://www.signsexpress.co.uk/stockport'}] },
    { id:'wayf', ph:'3', item:'Internal wayfinding, the house rules panel, vinyls, the signature wall lettering', note:'Set in Chivo, yellow on charcoal. Includes the LED feature sign at reception (£400–£1,500).', who:'Same sign company; artwork in-house', low:1500, mid:2500, high:4000, tag:'est.' },
    { id:'water', ph:'3', item:'Two bottle-refill stations, plumbed', note:'Elkay ezH2O surface-mount £1,506 inc VAT (about £1,255 ex) to £3,995 top models; installation £300–£800 each.', who:'Elkay via Water Refill Group · Zip HydroChill · Borg & Overström · MIW', low:2500, mid:4000, high:7000, src:[{t:'waterrefillgroup.com',u:'https://waterrefillgroup.com/collections/indoor-bottle-filling-stations'}] },

    /* ---- 4 · Fit and equip ---- */
    { id:'kit', ph:'4', item:'Training equipment — 20 strength stations, 8 racks with platforms, bars and plates, dumbbells 2.5–50 kg, 10 benches, 12 cardio pieces, accessories', note:'Value: Chinese OEM landed plus Primal and refurbished cardio. Mid: Primal Performance / Origin Performance strength, Matrix Performance cardio, Concept2 and Rogue Echo. Premium: Hammer Strength, Life Fitness Signature, Watson, Prime, Gymleco, Eleiko bars and discs, Integrity+ treadmills. Unit prices and the tier build-ups are on the one-off costs page. Twelve-week lead on Hammer Strength; order at the end of the design phase.', who:'UK: Primal Strength (Sheffield) · Origin Fitness (Edinburgh) · Watson Gym Equipment (Frome) · Life Fitness / Hammer Strength via FitKit UK, Fitness Superstore, Pinnacle · Matrix Fitness UK · Technogym UK · Pulse Fitness (Cheshire) · Eleiko UK · Rogue Europe · Gymleco (via Equip4Gyms) · Prime (via Staffs Fitness) · Arsenal Strength UK · BLK BOX · Wolverson · Jordan, Physical Company, Gym Gear (accessories) · refurbished: Gymkit UK, UK Gym Equipment Ltd, Pinnacle Fitness, FitKit used, Amazon Leisure', low:105000, mid:195000, high:330000, src:[{t:'originfitness.com',u:'https://originfitness.com/'},{t:'primalstrength.com',u:'https://www.primalstrength.com/'},{t:'fitkituk.com Hammer Strength',u:'https://www.fitkituk.com/'},{t:'fitness-superstore.co.uk Matrix / Life Fitness',u:'https://www.fitness-superstore.co.uk/'},{t:'concept2 UK',u:'https://concept2uk.zendesk.com/'},{t:'roguefitness.com/gb',u:'https://www.roguefitness.com/gb/'}] },
    { id:'inst', ph:'4', item:'Equipment delivery, forklift, assembly', note:'Two fitters at about £250 a day for 6–8 days, forklift hire £250–£400 a day; specialist gym logistics £500–£3,000 for a small install, far more for a multi-storey city job.', who:'Supplier\'s own install team · Gym Equipment Logistics (national)', low:4000, mid:7000, high:10000, src:[{t:'gymequipmentlogistics.co.uk',u:'https://gymequipmentlogistics.co.uk/'}] },
    { id:'door', ph:'4', item:'Access control — QR/NFC reader door, controller, fail-safe maglock, exit sensor, break-glass, anti-tailgate camera', note:'Single-leaf reader door £1,500–£3,500 installed, integrated to our software over OSDP or API (Suprema XPass Q2 reads QR natively; Paxton Net2 and ZKTeco QR500 are alternatives). A speed-gate lane is £8–20k and photographs like an airport. Include a plain fob reader as the fallback.', who:'Suprema · Paxton via a Net2 installer · HID Signo · ZKTeco · door hardware: Door Controls Direct · monitored service alternative: GymSecure (£130/month)', low:2000, mid:3000, high:12000, src:[{t:'nortechcontrol.com access control costs',u:'https://blog.nortechcontrol.com/'},{t:'gymsecure.co.uk',u:'https://gymsecure.co.uk/'}] },
    { id:'panic', ph:'4', item:'Panic hardware on every escape door, fixed panic buttons', note:'BS EN 1125 push bars £80–£350 per door; wired panic buttons £40–£150 each.', who:'Door hardware via the main contractor; buttons via the alarm installer', low:600, mid:1000, high:1800, tag:'est.' },
    { id:'cctv', ph:'4', item:'CCTV — 16–24 IP cameras, NVR, remote access', note:'16-camera commercial systems £4,000–£10,000+; £300–£750 per camera installed. Insurers require it for unstaffed hours.', who:'Hikvision or Dahua via an NSI installer (value) · Axis (premium) · Verkada (cloud, plus £100–£200 per camera per year)', low:5000, mid:9000, high:15000, src:[{t:'dcsecurity.co.uk',u:'https://www.dcsecurity.co.uk/'},{t:'ussgl.co.uk',u:'https://www.ussgl.co.uk/'}] },
    { id:'alarm', ph:'4', item:'Intruder alarm, Grade 2, dual-path signalling, police URN', note:'£1,500–£3,000 installed; URN fee about £46 one-off.', who:'NSI/SSAIB installer (Hawthorne Systems and others)', low:1500, mid:2200, high:3000, src:[{t:'hawthorne-systems.co.uk',u:'https://hawthorne-systems.co.uk/'}] },
    { id:'aed', ph:'4', item:'Defibrillator, cabinet, signage, registration on The Circuit', note:'iPAD SP1 about £920 ex VAT, Philips HeartStart £845, Zoll AED 3 £1,285; cabinet £120–£600. ukactive/BHF guidance (May 2026) sets the standard: reachable within three minutes from any point, signed, registered, checked weekly.', who:'defibshop.co.uk · defibstore.co.uk · Direct365', low:1100, mid:1600, high:2200, src:[{t:'ukactive/BHF defibrillator guidance, May 2026',u:'https://ukactive.com/'},{t:'defibstore.co.uk',u:'https://www.defibstore.co.uk/'}] },
    { id:'inter', ph:'4', item:'Emergency intercom to the monitoring centre, body-worn camera for single-staffed shifts', note:'Intercom £150–£900; body-worn £100–£500.', who:'Commend / SIP intercom on the network · Reveal, Hytera', low:400, mid:800, high:1400, tag:'est.' },
    { id:'net', ph:'4', item:'Network — rack, PoE switch, UPS, five Wi-Fi access points, 5G failover router', note:'UniFi has no licence fees (£100–£300 per AP); Aruba Instant On similar; Meraki adds £100–£200 per AP per year. Teltonika RUTX50 5G router about £375.', who:'Ubiquiti UniFi via a local installer · Teltonika · APC UPS', low:2500, mid:4000, high:7000, src:[{t:'pioneer-solutions.co.uk',u:'https://pioneer-solutions.co.uk/'},{t:'drakos-systems.co.uk',u:'https://drakos-systems.co.uk/'}] },
    { id:'pa', ph:'4', item:'Zoned sound — four-zone amplifier, 8–12 ceiling or pendant speakers, streamer', note:'Kit only £480–£3,000; installed £2,500–£8,000. Sonos is consumer kit and is not licensed for commercial background music on its own.', who:'Optimal Audio · Cloud Electronics · PD via audiovolt.co.uk · install by the AV or electrical contractor', low:2500, mid:4000, high:8000, src:[{t:'optimal-audio.co.uk',u:'https://optimal-audio.co.uk/'},{t:'audiovolt.co.uk',u:'https://audiovolt.co.uk/'}] },
    { id:'screens', ph:'4', item:'Digital screens — 2 × 55", 2 × 43", 1 × 32" touch kiosk, 1 × 32" portrait, mounts and install', note:'Commercial 55" £850–£1,400, 43" £550–£900 (UK estimates from US street prices); floor kiosk 32" £1,200–£2,500; mount and install £150–£600 per screen. Signage CMS is a monthly line.', who:'Samsung QM/QB · LG UH5 · Philips Q-line via Screentap, Strive AV or a Manchester AV integrator · CMS: Yodeck, ScreenCloud, OptiSigns', low:5000, mid:8000, high:12000, src:[{t:'screentap.co.uk',u:'https://screentap.co.uk/'},{t:'yodeck.com pricing',u:'https://www.yodeck.com/'}], tag:'est.' },
    { id:'tags', ph:'4', item:'Machine tags — 80 on-metal NFC discs and 80 anodised QR plates', note:'On-metal NTAG213 £1.20–£2.50 each; industrial epoxy £2–£5; anodised aluminium QR plates £2–£8 each. Lock tags read-only after encoding.', who:'Seritag · NFC Tagify · RapidNFC (tags) · Data-Plates · Nameplates.co.uk · Brunel Engraving (plates)', low:300, mid:500, high:1000, src:[{t:'seritag.com on-metal NTAG213',u:'https://seritag.com/nfc-tags/22mm-onmetal-ntag213'}] },
    { id:'furn', ph:'4', item:'Reception desk, lounge seating, planting, the signature wall', note:'Catalogue desks £170–£1,870; bespoke £3–8k. Six lounge seats, a bench, planting £2–6k.', who:'Nokk UK · Gymkit Fit Interiors (bespoke desks) · Think Office Furniture (catalogue) · a local joiner for the slat wall', low:4000, mid:9000, high:16000, src:[{t:'nokk.co.uk gym reception desks',u:'https://nokk.co.uk/products/gym-reception-desks/'}], tag:'est.' },
    { id:'creator', ph:'4', item:'Two creator zones — key lights, phone shelves and mounts, matte backdrop, painted feature wall', note:'Backdrop kits £39–£235; two LED panels, a wall-mounted arm and a shelf per zone. The slat screens are in the joinery line.', who:'Essential Photo · Backdropsource · Manfrotto/Neewer via Wex', low:1500, mid:3000, high:6000, src:[{t:'essentialphoto.co.uk',u:'https://www.essentialphoto.co.uk/'}], tag:'est.' },
    { id:'recov', ph:'4', item:'Recovery kit — one massage chair, two pairs of compression boots, one red-light panel', note:'Vending massage chair: VComfort £499 set-up on an income share, or buy £3–5k with a card reader. Normatec 3 £899, Therabody JetBoots £799 (retail, inc VAT). Red-light panels £1,250–£12,000. Premium adds a 3–4 person infrared sauna (£3,500–£6,500) which needs extract and a hard-wired circuit. No cold plunge: it is a pool under HSG179 if unattended.', who:'VComfort · NAIPO · Hyperice · Therabody · Red Light Rising · Peak Saunas / Telos Wellness', low:2500, mid:7000, high:25000, src:[{t:'vcomfort.co.uk vending chairs',u:'https://www.vcomfort.co.uk/pages/vending-massage-chairs'},{t:'healthclubmanagement.co.uk on red-light panels',u:'https://www.healthclubmanagement.co.uk/'}] },
    { id:'vend', ph:'4', item:'Vending — two machines', note:'Operator-supplied on a free-on-loan deal at £0 capital when footfall qualifies (value and mid). Buying a snack/can combo with card reader £3–6k; a protein shake machine £4–8k.', who:'Broderick\'s (Manchester) · Selecta · Vending Sense · Pro-Vend (shakes)', low:0, mid:0, high:9000, src:[{t:'brodericks.co.uk',u:'https://brodericks.co.uk/vending-machines/'}] },
    { id:'pos', ph:'4', item:'Front desk till and card terminal', note:'NeroPay terminal and NeroPOS, at cost to the group. Not priced here by rule.', who:'NeroPay', low:0, mid:0, high:0, tag:'in-house' },

    /* ---- 5 · Comply, insure, staff ---- */
    { id:'fra', ph:'5', item:'Fire risk assessment, recorded in full', note:'Legally required in full regardless of headcount since 1 Oct 2023; penalties unlimited. £400–£1,200 for a 24/7 gym with showers and plant.', who:'IFE-registered assessor (Fire Risk Assessment Network members)', low:400, mid:650, high:1200, src:[{t:'fire-risk-assessment-network.com',u:'https://www.fire-risk-assessment-network.com/'}] },
    { id:'leg', ph:'5', item:'Legionella risk assessment and written scheme', note:'Showers and a stored hot-water system. £350–£1,000.', who:'LCA-registered contractor', low:350, mid:550, high:1000, src:[{t:'urisk.co.uk',u:'https://urisk.co.uk/'}] },
    { id:'pat', ph:'5', item:'PAT testing of ~150 items, fire alarm and emergency lighting commissioning certificates', note:'PAT £1–£3 per item; certificates usually inside the electrical contract.', who:'Electrical contractor', low:200, mid:350, high:600, src:[{t:'direct365.co.uk',u:'https://www.direct365.co.uk/'}] },
    { id:'music', ph:'5', item:'TheMusicLicence (PPL PRS), first year', note:'£747.29 a year for up to 249 m²; the 250–499 m² band is not published — £1,100–£1,500 estimated. Soundtrack Your Brand (£39/month) does not replace it.', who:'PPL PRS Ltd', low:1000, mid:1290, high:1500, src:[{t:'pplprs.co.uk gyms',u:'https://pplprs.co.uk/themusiclicence/sectors/fitness-dance-2/gyms-fitness-and-dance-studios/'}], tag:'band est.' },
    { id:'lic', ph:'5', item:'TV licence, ICO fee, food registration for vending', note:'TV licence £180 (only if any screen shows live TV); ICO Tier 1 £52 or Tier 2 £78; food registration free, 28 days before trading.', who:'TV Licensing · ICO · Stockport MBC', low:60, mid:260, high:260, src:[{t:'ico.org.uk fee tiers',u:'https://ico.org.uk/'}] },
    { id:'ins', ph:'5', item:'Insurance — first premium instalment', note:'Annual package £2,500–£8,000: public liability £5–10m, employers\' liability, contents £150–250k, business interruption, cyber for our own membership software. Insurers require CCTV to every area, panic buttons or lanyards, photo ID, 18+ during unstaffed hours. Monthly cost is on the running page; this is the deposit.', who:'Insure4Sport · Protectivity · Fitness Gold (Salon Gold) · Simply Business · Hiscox · Sports Insure · brokers: Towergate, Gallagher, Marsh Commercial, Pulse Insurance, BGi.uk', low:250, mid:450, high:800, src:[{t:'bionic.co.uk gym insurance',u:'https://bionic.co.uk/business-insurance/gyms/'},{t:'gym-insurance.co.uk 24hr conditions',u:'https://gym-insurance.co.uk/'}], tag:'est.' },
    { id:'tandc', ph:'5', item:'Membership terms compliant with OFT v Ashbourne and CMA37', note:'OFT373 is withdrawn. Minimum terms of 12 months or less with genuine exit provisions, no acceleration penalties, plain 30-day notice. Most templates still cite the withdrawn guidance.', who:'Consumer-law solicitor', low:750, mid:1500, high:2500, src:[{t:'OFT v Ashbourne [2011] note, lexology.com',u:'https://www.lexology.com/'}], tag:'est.' },
    { id:'ptlic', ph:'5', item:'PT licence agreement drafted by an employment solicitor', note:'Fixed rent, no rostered shifts, no price-setting, genuine right of substitution. A 2017 tribunal found worker status for a PT who paid no rent and got no pay, on control alone. The only ancillary line whose liability exceeds its revenue if done casually.', who:'Employment solicitor', low:500, mid:1000, high:1500, tag:'est.' },
    { id:'recruit', ph:'5', item:'Recruitment — GM, duty manager, hosts, cleaner', note:'Reed from £89 an advert, Totaljobs ~£219, Indeed pay-per-click; DBS basic £21.50; £300–£600 all-in per hire.', who:'Reed · Indeed · Leisurejobs · DBS via an umbrella body', low:1000, mid:2000, high:3500, src:[{t:'treegarden.io UK job board comparison',u:'https://treegarden.io/blog/uk-job-boards-comparison/'},{t:'gov.uk DBS fees Oct 2026',u:'https://www.gov.uk/government/news/dbs-reduces-fees-for-checks-and-update-service-from-5-october-2026'}] },
    { id:'train', ph:'5', item:'Training — First Aid at Work × 3, AED, Level 2 top-ups, induction week', note:'FAW 3-day £199–£359 + VAT; EFAW £95–£115; Level 2 Gym Instructor £449–£895.', who:'St John Ambulance · Red Cross · CST Training · The Fitness Group / Origym for Level 2', low:1000, mid:2000, high:3500, src:[{t:'redcrossfirstaidtraining.co.uk',u:'https://www.redcrossfirstaidtraining.co.uk/'},{t:'thefitnessgrp.co.uk',u:'https://www.thefitnessgrp.co.uk/'}] },
    { id:'unif', ph:'5', item:'Uniforms — two polos and a hoodie per head, embroidered', note:'£60–£100 a head for six people.', who:'Workwear Express · Clothes2Order (Manchester) · Stanley/Stella blanks via a local embroiderer', low:400, mid:600, high:1000, tag:'est.' },
    { id:'prewage', ph:'5', item:'Pre-opening wages — GM two months before opening, duty manager one month', note:'GM £30–38k, duty manager £25–29k in Greater Manchester (estimates; job boards were not readable in the session), plus 15% NI above £417 a month.', who:'—', low:5500, mid:8000, high:11000, tag:'est.' },
    { id:'kits', ph:'5', item:'First-aid kits (BS 8599-1:2019+A1:2026), cleaning equipment, opening consumables, hygiene stations', note:'Three wipe dispensers, sanitiser stations, bins, a floor scrubber, first stock of paper and chemicals.', who:'Safetec · Direct365 · Nisbets', low:1200, mid:2000, high:3500, tag:'est.' },

    /* ---- 6 · Software and pre-sale ---- */
    { id:'sw', ph:'6', item:'Phase 1 software — join, Direct Debit mandate, QR entry, bookings, member app', note:'Built in-house, so £0 cash in value and mid. The premium column shows what a contractor would charge for the same scope (£30–60k), which is also the honest opportunity cost of Eray\'s time. Apple developer account $99/year, Google Play $25 one-off.', who:'NeroPay engineering · Direct Debit rails behind our interface: GoCardless (1% + 20p capped £4) or Access PaySuite (~43p per collection at 500 members)', low:100, mid:100, high:45000, src:[{t:'gocardless.com/pricing',u:'https://gocardless.com/pricing'},{t:'accesspaysuite.com',u:'https://www.accesspaysuite.com/'}], tag:'in-house', tagc:'yl' },
    { id:'presale', ph:'6', item:'Pre-sale — hoarding wrap, banners, 20,000 leaflets, launch event, three months of paid social', note:'Royal Mail Door to Door £30–£65 per 1,000 (min £200 + VAT); PVC banners £60–£150; a 20 m hoarding wrap £1,500–£3,000; Meta CPL for fitness $28–$50 in 2025–26; launch event £500–£1,500. Detail on the marketing page.', who:'Royal Mail Door to Door · Signs Express (hoarding) · Meta Ads in-house · a local photographer for the build diary', low:4000, mid:6500, high:10000, src:[{t:'royalmail.com door-to-door pricing',u:'https://www.royalmail.com/business-campaign/door-to-door/leaflet-distribution-pricing'},{t:'twobrainbusiness.com paid ads guide',u:'https://twobrainbusiness.com/paid-ads-guide/'}] },
    { id:'creatorprog', ph:'6', item:'Creator programme — ten local creators, six months', note:'Micro-influencer rates £250–£1,000 an Instagram post, £300–£1,200 a TikTok. Ours is mostly access and a member rate, plus a small fee for the launch week content.', who:'Direct outreach; contracts on a simple release', low:1000, mid:2500, high:6000, src:[{t:'aether-agency.co.uk UK influencer rate card 2026',u:'https://aether-agency.co.uk/insights/influencer-rate-card-uk-2026'}], tag:'est.' },
    { id:'photo', ph:'6', item:'Launch photography and film of the finished room', note:'One day, two people, the assets every post for a year comes from.', who:'A Manchester architectural photographer; film via the existing HyperFrames pipeline', low:600, mid:1200, high:2500, tag:'est.' },

    /* ---- 7 · Contingency and reserve ---- */
    { id:'cont', ph:'7', item:'Build contingency — 10% of build, fit and equipment', note:'What the asbestos survey missed, the drain that runs the wrong way, the extra sub-main.', who:'—', low:32000, mid:55000, high:97000, tag:'10%' },
    { id:'reserve', ph:'7', item:'Cash reserve — six months of running costs before rent', note:'The ramp modelled with 280 pre-sold members reaches its worst cash position around month four. Without this line the gym is solvent on paper and insolvent in April.', who:'—', low:75000, mid:104000, high:140000, tag:'6 × opex', tagc:'yl' }
  ],

  /* ---- monthly running costs, ex rent. g = group. var:true rows are modelled as variables, not fixed cost. ---- */
  opex: [
    { id:'sc', g:'Premises (X excluded)', item:'Service charge and insurance rent to the landlord', note:'£1.00–£1.50 per sq ft a year on a secondary industrial estate; estimate.', who:'Landlord', low:420, mid:520, high:625, tag:'est.' },
    { id:'rates', g:'Premises (X excluded)', item:'Business rates', note:'Gyms qualify for the retail, hospitality and leisure multiplier: 38.2p below £51k rateable value in 2026/27. RV is rent-based: £30k → £955; £35k → £1,114; £45k → £1,433 a month. If the council does not accept RHL, 43.2p applies. Small business relief ends at £15k RV so it does not help.', who:'Stockport MBC', low:955, mid:1114, high:1433, src:[{t:'gov.uk RHL multipliers 2026/27',u:'https://www.gov.uk/guidance/business-rates-multipliers-qualifying-retail-hospitality-or-leisure'}] },
    { id:'energy', g:'Premises (X excluded)', item:'Electricity and gas', note:'Small-business electricity 27–30p/kWh (Aug 2026 average 29.6p) plus CCL 0.801p and standing charges; gas 8.5–9p. A 24/7 465 m² strength gym with LED and a heat-pump is modelled at 75,000–110,000 kWh electricity a year plus hot water for 40 showers a day. CIBSE TM46 fitness benchmark (160 kWh/m² electric, 200 thermal) recalled, not re-read.', who:'Broker (Bionic, Utility Bidder) or direct; solar PV on the roof at £850–£1,100/kWp pays back in 5–8 years on a 24/7 baseload', low:2400, mid:3000, high:3800, src:[{t:'aquaswitch.co.uk business electricity Sept 2026',u:'https://www.aquaswitch.co.uk/business-electricity-prices/'},{t:'energycosts.co.uk gym sector',u:'https://www.energycosts.co.uk/sectors/gym'}], tag:'est.' },
    { id:'wat', g:'Premises (X excluded)', item:'Water and sewerage', note:'About 4 m³ a day with 40 showers; United Utilities wholesale via a retailer. 2026/27 £/m³ not readable in the session; estimate.', who:'Water Plus · Everflow · Castle Water · Business Stream · Wave', low:450, mid:550, high:650, src:[{t:'aquaswitch.co.uk business water',u:'https://www.aquaswitch.co.uk/business-water-rates/'}], tag:'est.' },
    { id:'waste', g:'Premises (X excluded)', item:'Waste and recycling — one 1,100 L weekly plus fortnightly recycling', note:'£20–£50 a lift, bin rental £80–£140 a year.', who:'Biffa · Veolia · Suez · a local carrier', low:150, mid:180, high:220, src:[{t:'expertsure.com commercial waste',u:'https://www.expertsure.com/uk/commercial-waste/collection-costs/'}] },
    { id:'pest', g:'Premises (X excluded)', item:'Pest control contract', who:'Rentokil or a local firm', low:30, mid:45, high:60, tag:'est.' },

    { id:'staff', g:'People', item:'Staff — three models', note:'Lean: 8 staffed hours a day, GM plus a weekend host (2 heads, ~£47k a year). Mid: GM, full-time duty manager, weekend host, ~80 staffed hours (3 heads, ~£78k). Full: staffed 06:00–22:00 daily with a second person 17:00–21:00 weekdays (5 heads, ~£112k). Hosts at £13.00/hr with 12.07% holiday, NI 15% above £5,000, £10,500 Employment Allowance, 3% pension. NLW £12.71 from 1 Apr 2026.', who:'—', low:3930, mid:6500, high:9350, src:[{t:'gov.uk NLW £12.71 from April 2026',u:'https://www.gov.uk/government/news/lpc-recommendations-take-the-national-living-wage-to-1271'}] },
    { id:'clean', g:'People', item:'Contract cleaning — 2 hours a day (lean) to 4 hours a day (full), seven days', note:'Manchester contract rates £16–£22 an hour; £19 used.', who:'A local contract cleaner; Clean Space guide for rates', low:1155, mid:1700, high:2310, src:[{t:'thecleanspace.com Manchester guide',u:'https://thecleanspace.com/contract-cleaning-manchester-guide/'}] },
    { id:'cons', g:'People', item:'Washroom services and consumables — sanitary bins, air care, gym wipes, paper, soap, chemicals', note:'Sanitary bins £8–£15 per bin per visit; wipe rolls £25–£35 each, 8–10 a month at 500 members.', who:'phs · Initial · Citron (washroom) · Nisbets / Direct365 (consumables)', low:400, mid:550, high:700, src:[{t:'hygieneplusbin.co.uk',u:'https://hygieneplusbin.co.uk/sanitary-bin-cost-uk'}], tag:'est.' },
    { id:'hr', g:'People', item:'Ongoing training, DBS renewals, uniform replacement', who:'—', low:100, mid:150, high:250, tag:'est.' },

    { id:'maint', g:'Upkeep', item:'Maintenance reserve — equipment PPM and parts, building compliance', note:'Equipment: £60–£120 per machine inspection, two visits a year, parts at 1.5–2% of fleet value; reactive-only costs 25–30% more per machine (PSLT 2026). Building: fire alarm 6-monthly, emergency lighting annual, HVAC service, legionella monitoring, EICR cycle, CCTV/alarm maintenance at 5–15% of install. The 48-hour repair promise lives here.', who:'Supplier PPM (Origin, Life Fitness, Matrix) or independents: Gym Equipment Servicing, Gym Service UK, Servicesport', low:800, mid:1000, high:1200, src:[{t:'gym-equipment-servicing.uk',u:'https://gym-equipment-servicing.uk/'},{t:'PSLT servicing report via healthclubmanagement.co.uk',u:'https://www.healthclubmanagement.co.uk/'}] },

    { id:'mon', g:'Safety and security', item:'Remote CCTV monitoring of unstaffed hours, panic response', note:'Gym-specialist monitoring £1.50–£1.57 an hour (Secure 24, GymSafe). Lean has the most unstaffed hours, full the fewest.', who:'Secure 24 · GymSafe (PSM)', low:750, mid:550, high:400, src:[{t:'secure24.co.uk',u:'https://secure24.co.uk/'},{t:'gym-safe.co.uk',u:'https://gym-safe.co.uk/'}] },
    { id:'sec', g:'Safety and security', item:'Alarm monitoring, keyholding, lone-worker seats', note:'Monitored alarm with police response £20–£40; keyholding £30–£80; lone-worker app £7–£15 a seat.', who:'Installer\'s ARC · Peoplesafe · StaySafe', low:120, mid:180, high:250, src:[{t:'alarmmonitoring.co.uk costs',u:'https://www.alarmmonitoring.co.uk/costs/'}] },

    { id:'dd', g:'Software and payments', item:'Direct Debit collection', note:'GoCardless Standard 1% + 20p capped £4 → about 48p per member per month at £45. Incumbents\' bureaux (Harlands, Ashbourne, DFC) charge the member £25 per failed payment; we do not.', who:'GoCardless · Access PaySuite · London & Zurich', low:200, mid:250, high:300, src:[{t:'gocardless.com/pricing',u:'https://gocardless.com/pricing'}] },
    { id:'card', g:'Software and payments', item:'Card acquiring on counter sales', note:'On our own terminal; rate not stated here by rule.', who:'NeroPay', low:25, mid:35, high:45, tag:'in-house' },
    { id:'cms', g:'Software and payments', item:'Digital signage CMS — six screens', note:'Yodeck $8–$15 a screen; ScreenCloud $20–$30; Xibo self-hosted £0.', who:'Yodeck · OptiSigns · ScreenCloud', low:40, mid:60, high:90, src:[{t:'yodeck.com',u:'https://www.yodeck.com/'}] },
    { id:'mus', g:'Software and payments', item:'Music — PPL PRS licence spread monthly, plus a business streaming service', note:'Licence £1,000–£1,500 a year for the 250–499 m² band (estimated); Soundtrack Your Brand £39 a month on top.', who:'PPL PRS · Soundtrack Your Brand / Ambie', low:120, mid:150, high:170, src:[{t:'pplprs.co.uk',u:'https://pplprs.co.uk/'}], tag:'band est.' },
    { id:'saas', g:'Software and payments', item:'Xero, Google Workspace, email/SMS, hosting, app store accounts', note:'Xero Grow £37; Workspace £5.90 a seat; Brevo-type email £15–£50; UK SMS 4–5p each.', who:'Xero · Google · Brevo · Vercel', low:100, mid:140, high:190, src:[{t:'aceybookkeeping.co.uk Xero pricing 2026',u:'https://aceybookkeeping.co.uk/xero-pricing-uk-2026/'}] },

    { id:'insm', g:'Insurance and professional', item:'Insurance package', note:'£2,500–£8,000 a year across public and employers\' liability, contents, business interruption and cyber.', who:'See the one-off ledger for insurers', low:210, mid:375, high:670, tag:'est.' },
    { id:'acc', g:'Insurance and professional', item:'Accountant, payroll, VAT returns', note:'Compliance-only £600–£1,500 a year; with VAT and payroll £150–£300 a month.', who:'Existing NeroPay accountant', low:100, mid:150, high:300, src:[{t:'ltd-companies.co.uk',u:'https://www.ltd-companies.co.uk/'}] },
    { id:'lic2', g:'Insurance and professional', item:'ICO fee, TV licence, legal reserve', who:'—', low:70, mid:120, high:170, tag:'est.' },

    { id:'mkt', g:'Marketing', item:'Steady-state marketing — paid social, referral credits, content', note:'The model treats this as churn × members × cost per acquisition (the cost of standing still) rather than this fixed figure; this row shows the scale and is excluded from the fixed-cost total the model uses.', who:'In-house on Meta and Google; a local photographer quarterly', low:800, mid:1200, high:2000, var:true, src:[{t:'sbc-performance.com UK Meta costs 2026',u:'https://sbc-performance.com/blog/facebook-ads-cost/'}] },

    { id:'misc', g:'Sundries', item:'Bank, stationery, uniforms, small tools', who:'Starling or Tide (free tier)', low:30, mid:55, high:75, tag:'est.' }
  ],

  /* ---- monthly ancillary income at steady state ---- */
  ancillary: [
    { id:'pt', item:'PT floor licences — six PTs', note:'£250–£350 a month each; PureGym charges ~£550, Gymbox £600–£900. A PT billing twenty Manchester sessions a week grosses about £3,200.', low:1200, mid:1800, high:2400 },
    { id:'vendinc', item:'Vending commission or margin', note:'£250–£400 revenue per machine a month; operator commission on two machines, or 25–35% net if owned.', low:80, mid:120, high:250 },
    { id:'recinc', item:'Recovery add-on and pay-per-use', note:'£8 a month add-on on lower tiers; massage chair £3 per 10 minutes. Utilisation unpublished anywhere; the mid case assumes 15% of members take the add-on.', low:100, mid:400, high:800 },
    { id:'day', item:'Day and week passes, guest fees', note:'£12 a day, £30 a week.', low:100, mid:200, high:400 }
  ],

  /* ---- model assumptions (carried from the September model where they exist) ---- */
  assump: {
    vat: 0.20,             // memberships are standard-rated
    realisation: 0.86,     // achieved ARPM vs headline: The Gym Group £22.14 achieved against £25.64 headline
    churn: 0.045,          // monthly; TGG H1 2026 tenure 18.5 months = 5.4%, market 21–26 months
    cpa: 80,               // £ per gross join, blended paid and referral; UK Meta fitness CPL $28–50, 30–50% trial-to-member
    collection: 0.016,     // Direct Debit collection as share of membership revenue (GoCardless Standard)
    varPerMember: 0.60,    // wipes, paper, water, tags — per member per month
    sqftPerMember: 10,     // the premium-feel cap; budget chains run ~3.3
    ramp: { presold: 250, joinsPerMonth: 45, months: 30 }
  },

  /* ---- the price plans the model can switch between ---- */
  price: {
    default: 49.99,
    plans: [
      { id:'foundry', name:'Fight Foundry', head:29.99, blend:29.99, note:'Single 24/7 price two pounds under Foundry\'s £31.99. Same product as a better-capitalised chain, opened later.' },
      { id:'single', name:'Single £34.99', head:34.99, blend:34.99, note:'The original brief. Above PureGym and The Gym Group, level with Life Leisure, under Zeno.' },
      { id:'tiered', name:'Tiered, blended ~£44', head:44.99, blend:43.99, note:'Off-peak/student £34.99 · Core 24/7 £44.99 · Plus with recovery and creator priority £54.99. Mix 30/50/20.' },
      { id:'strength', name:'Strength House £49.99', head:49.99, blend:48.99, note:'Off-peak/student £39.99 · Core £49.99 · Plus £59.99. Mix 25/55/20. The September model\'s recommendation.' },
      { id:'prem', name:'Premium £59.99', head:59.99, blend:57.49, note:'Off-peak £44.99 · Core £59.99 · Plus £69.99. Boutique money for a strength room; Zeno is £51.' }
    ]
  },

  /* ---- competitor register, September 2026, monthly rolling headline ---- */
  competitors: [
    { name:'The Gym Group Stockport (Redrock)', price:17.99, join:15, h24:true, dist:'town centre', src:'thegymgroup.com, snippet 16 Sep 2026' },
    { name:'PureGym Stockport North (Didsbury Rd)', price:19.99, join:0, h24:true, dist:'~2 mi', src:'puregym.com, promo live 16 Sep 2026' },
    { name:'PureGym Stockport South', price:20.99, join:0, h24:true, dist:'—', src:'puregym.com' },
    { name:'JD Gyms (nearest: Wythenshawe / Manchester City £29.99)', price:27.99, join:0, h24:null, dist:'~6–7 mi', src:'jdgyms.co.uk; Middleton £27.99' },
    { name:'PureGym Gee Cross', price:27.99, join:15, h24:true, dist:'~4 mi', src:'puregym.com/join' },
    { name:'Foundry Stockport (opens Nov 2026)', price:31.99, join:0, h24:true, dist:'town centre', src:'prior research, Sept 2026' },
    { name:'Life Leisure (ten Stockport sites)', price:37, join:null, h24:false, dist:'0–4 mi', src:'prior research: £30–44 band, midpoint shown' },
    { name:'Zeno (formerly Hero), Didsbury — boutique', price:51, join:null, h24:null, dist:'~4 mi', src:'themanc.com ranking; off-peak £43' },
    { name:'Nuffield Health Stockport', price:72, join:39, h24:false, dist:'~1 mi', src:'estate range £50–95, midpoint; joining up to £39' },
    { name:'Village Gym Cheadle', price:88, join:null, h24:false, dist:'~4 mi', src:'Hussle Monthly+ £87.60; official not published' },
    { name:'David Lloyd Cheadle', price:130, join:100, h24:false, dist:'~4 mi', src:'third-party guides £94.50–£200+; midpoint; joining £65–161' },
    { name:'F45 Manchester NQ', price:165, join:null, h24:false, dist:'~7 mi', src:'themanc.com; 6-month commitment' }
  ]
};
